# New York City Payroll


## Overview
Data from [NYC Open Data](https://data.cityofnewyork.us/City-Government/Citywide-Payroll-Data-Fiscal-Year-/k397-673e) representing New York City employee salary and overtime pay.

#### Imports

In [1]:
import pandas as pd
import numpy as np

#### Import data with dtype argument due to large file size

In [2]:
nyc_full = pd.read_csv('NYC_Payroll_Data.csv', dtype={'Fiscal Year': 'int', 'Payroll Number': 'float', 'Agency Name': 'str',
                                                            'Last Name': 'str','First Name': 'str','Mid Init': 'str',
                                                            'Agency Start Date': 'str','Work Location Borough': 'str','Title Description': 'str',
                                                            'Leave Status as of June 30': 'str','Base Salary': 'float','Pay Basis': 'str',
                                                            'Regular Hours': 'float', 'Regular Gross Paid': 'float', 'OT Hours': 'float',
                                                            'Total OT Paid': 'float', 'Total Other Pay': 'float'})

#### Make backup copy of data before making changes

In [3]:
nyc = nyc_full.copy()

#### Initial review of DataFrame

In [4]:
nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4496767 entries, 0 to 4496766
Data columns (total 17 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Fiscal Year                 int64
 1   Payroll Number              float64
 2   Agency Name                 object
 3   Last Name                   object
 4   First Name                  object
 5   Mid Init                    object
 6   Agency Start Date           object
 7   Work Location Borough       object
 8   Title Description           object
 9   Leave Status as of June 30  object
 10  Base Salary                 float64
 11  Pay Basis                   object
 12  Regular Hours               float64
 13  Regular Gross Paid          float64
 14  OT Hours                    float64
 15  Total OT Paid               float64
 16  Total Other Pay             float64
dtypes: float64(7), int64(1), object(9)
memory usage: 583.2+ MB

In [5]:
nyc.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2020,17.0,OFFICE OF EMERGENCY MANAGEMENT,BEREZIN,MIKHAIL,NaN,08/10/2015,BROOKLYN,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.0
1,2020,17.0,OFFICE OF EMERGENCY MANAGEMENT,GEAGER,VERONICA,M,09/12/2016,BROOKLYN,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.0
2,2020,17.0,OFFICE OF EMERGENCY MANAGEMENT,RAMANI,SHRADDHA,NaN,02/22/2016,BROOKLYN,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.0
3,2020,17.0,OFFICE OF EMERGENCY MANAGEMENT,ROTTA,JONATHAN,D,09/16/2013,BROOKLYN,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.0
4,2020,17.0,OFFICE OF EMERGENCY MANAGEMENT,WILSON II,ROBERT,P,04/30/2018,BROOKLYN,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.0

#### Transform characters to uppercase for consistency

In [6]:
def upper_case(df):
    '''
    Takes as input the `nyc` DataFrame. 
    Then capitalizes each character in columns with "object" data type.
    '''
    # iterating over each column in the DataFrame
    for col in df.columns:
        # checking datatype of each column
        if df[col].dtype == 'object':
            # applying upper function on column
            df[col] = df[col].str.upper()

upper_case(nyc)

#### Review shape of dataset

In [7]:
nyc.shape

(4496767, 17)

#### Create a DataFrame for 2021 fiscal year for further analysis

In [8]:
nyc_2021 = nyc.loc[nyc["Fiscal Year"] == 2021].copy()
nyc_2021.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
3923290,2021,996.0,NYC HOUSING AUTHORITY,MUSTACIUOLO,VITO,J,02/26/2018,MANHATTAN,EXECUTIVE DIRECTOR,ACTIVE,258000.0,PER ANNUM,1820.0,257260.30,0.00,0.00,258000.00
3923291,2021,996.0,NYC HOUSING AUTHORITY,RUSS,GREGORY,P,08/12/2019,MANHATTAN,CHAIR,ACTIVE,414707.0,PER ANNUM,1820.0,413518.05,0.00,0.00,500.00
3923292,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,MCGROARTY,MICHAEL,NaN,10/06/2014,QUEENS,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2374.75,238829.13,40105.00
3923293,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,HALLAHAN,PATRICK,M,02/26/2018,BROOKLYN,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2115.25,218628.18,56616.07
3923294,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,PETTIT,PATRICK,J,08/02/2010,MANHATTAN,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2152.75,218694.96,38611.82

#### Check number of people represented in 2021 fiscal year

In [9]:
len(nyc_2021.index)

573477

#### Review list sorted by highest base salary

In [10]:
nyc_2021.sort_values(by='Base Salary', ascending=False)

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
3923291,2021,996.0,NYC HOUSING AUTHORITY,RUSS,GREGORY,P,08/12/2019,MANHATTAN,CHAIR,ACTIVE,414707.0,PER ANNUM,1820.0,413518.05,0.0,0.0,500.00
3923347,2021,742.0,DEPT OF ED PEDAGOGICAL,CARRANZA,RICHARD,A,04/02/2018,MANHATTAN,ASSISTANT SUPERINTENDENT,CEASED,363346.0,PER ANNUM,0.0,272509.56,0.0,0.0,16696.67
3923490,2021,742.0,DEPT OF ED PEDAGOGICAL,ROSS PORTER,MEISHA,S,09/04/2001,MANHATTAN,CHANCELLOR,ACTIVE,363346.0,PER ANNUM,0.0,254354.83,0.0,0.0,-2481.99
3923299,2021,15.0,OFFICE OF THE COMPTROLLER,DONE,ALEXIS,NaN,03/12/2012,MANHATTAN,PENSION INVESTMENT ADVISOR,ACTIVE,350000.0,PER ANNUM,1820.0,349014.96,0.0,0.0,0.00
3923321,2021,8.0,OFFICE OF THE ACTUARY,CHAN,SHERRY,S,05/18/2015,MANHATTAN,CHIEF ACTUARY,ACTIVE,311885.0,PER ANNUM,1820.0,311007.12,0.0,0.0,-5974.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4414844,2021,300.0,BOARD OF ELECTION POLL WORKERS,BARNETT,CATHERINE,NaN,01/01/2020,MANHATTAN,ELECTION WORKER,ACTIVE,1.0,PER HOUR,0.0,350.00,0.0,0.0,0.00
4414843,2021,300.0,BOARD OF ELECTION POLL WORKERS,BARNES,WILLIE MAE,NaN,01/01/2020,MANHATTAN,ELECTION WORKER,ACTIVE,1.0,PER HOUR,0.0,350.00,0.0,0.0,0.00
4414858,2021,300.0,BOARD OF ELECTION POLL WORKERS,BARON,PAMELA,R,11/19/2020,MANHATTAN,ELECTION WORKER,ACTIVE,1.0,PER HOUR,0.0,350.00,0.0,0.0,0.00
4414857,2021,300.0,BOARD OF ELECTION POLL WORKERS,BARON,COURTNEY,NaN,01/01/2020,MANHATTAN,ELECTION WORKER,ACTIVE,1.0,PER HOUR,0.0,350.00,0.0,0.0,0.00
4414829,2021,300.0,BOARD OF ELECTION POLL WORKERS,BARKOVIC,EMILY,NaN,01/01/2020,MANHATTAN,ELECTION WORKER,ACTIVE,1.0,PER HOUR,0.0,350.00,0.0,0.0,0.00

#### Identify 5 employees with highest regular gross pay

In [11]:
nyc_2021.sort_values(by='Regular Gross Paid', ascending=False).head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
3923291,2021,996.0,NYC HOUSING AUTHORITY,RUSS,GREGORY,P,08/12/2019,MANHATTAN,CHAIR,ACTIVE,414707.0,PER ANNUM,1820.0,413518.05,0.0,0.00,500.00
3923299,2021,15.0,OFFICE OF THE COMPTROLLER,DONE,ALEXIS,NaN,03/12/2012,MANHATTAN,PENSION INVESTMENT ADVISOR,ACTIVE,350000.0,PER ANNUM,1820.0,349014.96,0.0,0.00,0.00
3923304,2021,67.0,ADMIN FOR CHILDREN'S SVCS,OKORO,EDWARD,NaN,06/23/1996,MANHATTAN,CHILD PROTECTIVE SPECIALIST,ON SEPARATION LEAVE,60351.0,PER ANNUM,1820.0,332518.52,4.0,661.91,-440.49
3923321,2021,8.0,OFFICE OF THE ACTUARY,CHAN,SHERRY,S,05/18/2015,MANHATTAN,CHIEF ACTUARY,ACTIVE,311885.0,PER ANNUM,1820.0,311007.12,0.0,0.00,-5974.80
3923329,2021,15.0,OFFICE OF THE COMPTROLLER,HADDAD,MICHAEL,D,01/11/2016,MANHATTAN,DIRECTOR OF INVESTMENTS,ACTIVE,300000.0,PER ANNUM,1820.0,299155.64,0.0,0.00,0.00

#### Review sorted by highest overtime total

In [12]:
nyc_2021.sort_values(by='Total OT Paid', ascending=False)

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
3923298,2021,996.0,NYC HOUSING AUTHORITY,PROCIDA,ROBERT,NaN,04/13/1987,BRONX,SUPERVISOR PLUMBER,ACTIVE,387.03,PER DAY,1820.00,100627.80,2249.50,248749.72,7215.34
3923292,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,MCGROARTY,MICHAEL,NaN,10/06/2014,QUEENS,STATIONARY ENGINEER,ACTIVE,508.80,PER DAY,2080.00,132288.00,2374.75,238829.13,40105.00
3923307,2021,996.0,NYC HOUSING AUTHORITY,MARKOWSKI,JAKUB,NaN,05/31/2016,BRONX,PLUMBER,ACTIVE,369.53,PER DAY,1820.00,96077.80,2119.50,223776.86,5899.29
3923294,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,PETTIT,PATRICK,J,08/02/2010,MANHATTAN,STATIONARY ENGINEER,ACTIVE,508.80,PER DAY,2080.00,132288.00,2152.75,218694.96,38611.82
3923293,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,HALLAHAN,PATRICK,M,02/26/2018,BROOKLYN,STATIONARY ENGINEER,ACTIVE,508.80,PER DAY,2080.00,132288.00,2115.25,218628.18,56616.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3976548,2021,56.0,POLICE DEPARTMENT,SCHNEIDER,SHEERA,A,07/01/2004,MANHATTAN,SERGEANT-,ACTIVE,109360.00,PER ANNUM,2121.92,111417.75,-66.05,-2638.77,16871.47
4132638,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,KIM,SEONGCHEOL,J,11/03/2014,QUEENS,PUBLIC HEALTH NURSE,ACTIVE,35.02,PER HOUR,1468.25,52084.98,-81.75,-2940.27,18162.56
3949090,2021,826.0,DEPT OF ENVIRONMENT PROTECTION,CASTIGLIONE,JOHN,A,04/22/2013,QUEENS,SUPERINTENDENT OF WATER AND SEWER SYSTEMS,ACTIVE,146260.00,PER ANNUM,1820.00,150156.32,0.00,-3944.42,-2801.90
4036978,2021,57.0,FIRE DEPARTMENT,FOGGIE JR,KENNETH,R,09/10/2018,BROOKLYN,COMMUNICATION ELECTRICIAN,ACTIVE,413.84,PER DAY,2080.00,107625.77,-65.00,-4780.75,51.44
4496739,2021,57.0,FIRE DEPARTMENT,KALTENMEIER,JOHN,W,09/14/1987,BROOKLYN,FIREFIGHTER,CEASED,85292.00,PER ANNUM,-5.72,-233.05,-132.00,-5022.29,-23835.73

#### Create 'Total Gross Paid' column to total regular gross, total overtime and total other pay

In [13]:
nyc_2021['Total Gross Paid'] = nyc_2021['Regular Gross Paid'] + nyc_2021['Total OT Paid'] + nyc_2021['Total Other Pay']

#### Verify change

In [14]:
nyc_2021

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Total Gross Paid
3923290,2021,996.0,NYC HOUSING AUTHORITY,MUSTACIUOLO,VITO,J,02/26/2018,MANHATTAN,EXECUTIVE DIRECTOR,ACTIVE,258000.0,PER ANNUM,1820.0,257260.30,0.00,0.00,258000.00,515260.30
3923291,2021,996.0,NYC HOUSING AUTHORITY,RUSS,GREGORY,P,08/12/2019,MANHATTAN,CHAIR,ACTIVE,414707.0,PER ANNUM,1820.0,413518.05,0.00,0.00,500.00,414018.05
3923292,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,MCGROARTY,MICHAEL,NaN,10/06/2014,QUEENS,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2374.75,238829.13,40105.00,411222.13
3923293,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,HALLAHAN,PATRICK,M,02/26/2018,BROOKLYN,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2115.25,218628.18,56616.07,407532.25
3923294,2021,816.0,DEPT OF HEALTH/MENTAL HYGIENE,PETTIT,PATRICK,J,08/02/2010,MANHATTAN,STATIONARY ENGINEER,ACTIVE,508.8,PER DAY,2080.0,132288.00,2152.75,218694.96,38611.82,389594.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496762,2021,742.0,DEPT OF ED PEDAGOGICAL,BURGAN,WYLIE,G,10/01/1986,OTHER,ASSISTANT PRINCIPAL,CEASED,124800.0,PER ANNUM,0.0,0.00,0.00,0.00,-71916.37,-71916.37
4496763,2021,902.0,BRONX DISTRICT ATTORNEY,SIMMONS,NATHANIEL,NaN,07/02/1990,BRONX,SPECIAL ASSISTANT TO THE DISTRICT ATTORNEY,CEASED,110000.0,PER ANNUM,-70.0,-4207.65,0.00,0.00,-75440.00,-79647.65
4496764,2021,742.0,DEPT OF ED PEDAGOGICAL,ROBERTSON,BRENDA,L,10/15/1985,OTHER,ASSISTANT PRINCIPAL,CEASED,126061.0,PER ANNUM,0.0,0.00,0.00,0.00,-87436.13,-87436.13
4496765,2021,742.0,DEPT OF ED PEDAGOGICAL,BECKHAM,DOLORES,NaN,11/04/1977,OTHER,PRINCIPAL,CEASED,159609.0,PER ANNUM,0.0,0.00,0.00,0.00,-97608.11,-97608.11
4496766,2021,740.0,DEPARTMENT OF EDUCATION ADMIN,CORLETT,SEAN,NaN,09/15/2013,MANHATTAN,ADMINISTRATIVE EDUCATION OFFICER,CEASED,143262.0,PER ANNUM,0.0,-117989.06,0.00,0.00,0.00,-117989.06

#### Calculate median total gross pay

In [15]:
nyc_2021['Total Gross Paid'].median()

np.float64(43359.15)

#### Calculate mean total gross pay

In [16]:
nyc_2021['Total Gross Paid'].mean()

np.float64(52017.993508580126)

#### Identify number of different agencies represented in 2021

In [17]:
nyc_2021['Agency Name'].nunique()

156

#### Determine which agencies had the highest / lowest median total gross pay

In [18]:
# Create a SeriesGroupBy object for total gross pay by agency

agency_total_gross_pay = nyc_2021['Total Gross Paid'].groupby(nyc_2021['Agency Name'])

In [19]:
agency_total_gross_pay

In [20]:
# Calculate median total gross pay by agency and sort highest to lowest

agency_total_gross_pay.median().sort_values(ascending=False)

Agency Name
FINANCIAL INFO SVCS AGENCY        120891.070
OFFICE OF COLLECTIVE BARGAININ    117705.070
BRONX COMMUNITY BOARD #3          111354.175
BRONX COMMUNITY BOARD #1          110795.435
DEPARTMENT OF SANITATION          108391.500
                                     ...
PUBLIC SERVICE CORPS                4462.810
PERSONNEL MONITORS                  1488.000
DEPT OF ED PER SESSION TEACHER       436.145
BOARD OF ELECTION POLL WORKERS       350.000
DEPARTMENT OF JUVENILE JUSTICE       102.900
Name: Total Gross Paid, Length: 156, dtype: float64

#### Calculate and compare highest individual total gross pay by agency

In [21]:
agency_total_gross_pay.max().sort_values(ascending=False)

Agency Name
NYC HOUSING AUTHORITY             515260.30
DEPT OF HEALTH/MENTAL HYGIENE     411222.13
GUTTMAN COMMUNITY COLLEGE         366923.01
POLICE DEPARTMENT                 358349.38
OFFICE OF THE COMPTROLLER         349014.96
                                    ...
BROOKLYN COMMUNITY BOARD #2        67381.41
BOARD OF ELECTION POLL WORKERS     55974.67
PERSONNEL MONITORS                 27688.00
PUBLIC SERVICE CORPS               10000.00
DEPARTMENT OF JUVENILE JUSTICE       102.90
Name: Total Gross Paid, Length: 156, dtype: float64

#### Identify the 5 highest paid employees (total gross pay) at Office of the Mayor

In [22]:
# filter employees from Office of the Mayor

nyc_mayor_office = nyc_2021[nyc_2021["Agency Name"] == 'OFFICE OF THE MAYOR']
nyc_mayor_office.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Total Gross Paid
3923357,2021,2.0,OFFICE OF THE MAYOR,FULEIHAN,DEAN,A,12/31/2017,MANHATTAN,FIRST DEPUTY MAYOR,ACTIVE,291139.0,PER ANNUM,1820.0,290319.68,0.0,0.0,-5577.40,284742.28
3923481,2021,2.0,OFFICE OF THE MAYOR,DE BLASIO,BILL,NaN,01/01/2014,MANHATTAN,MAYOR,ACTIVE,258750.0,PER ANNUM,1820.0,258021.79,0.0,0.0,-4956.90,253064.89
3923536,2021,2.0,OFFICE OF THE MAYOR,ANGLIN,LAURA,L,01/03/2017,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,PER ANNUM,1820.0,251272.70,0.0,0.0,-4827.25,246445.45
3923537,2021,2.0,OFFICE OF THE MAYOR,BEEN,VICKI,L,02/07/2017,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,PER ANNUM,1820.0,251272.70,0.0,0.0,-4827.25,246445.45
3923538,2021,2.0,OFFICE OF THE MAYOR,THOMPSON,JAMES,P,03/12/2018,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,PER ANNUM,1820.0,251272.70,0.0,0.0,-4827.25,246445.45

In [23]:
# Sort Office of the Mayor employees by highest total gross pay

nyc_mayor_office.sort_values(by = 'Total Gross Paid', ascending=False)

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Total Gross Paid
3923357,2021,2.0,OFFICE OF THE MAYOR,FULEIHAN,DEAN,A,12/31/2017,MANHATTAN,FIRST DEPUTY MAYOR,ACTIVE,291139.00,PER ANNUM,1820.00,290319.68,0.0,0.0,-5577.40,284742.28
3923481,2021,2.0,OFFICE OF THE MAYOR,DE BLASIO,BILL,NaN,01/01/2014,MANHATTAN,MAYOR,ACTIVE,258750.00,PER ANNUM,1820.00,258021.79,0.0,0.0,-4956.90,253064.89
3923538,2021,2.0,OFFICE OF THE MAYOR,THOMPSON,JAMES,P,03/12/2018,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.00,PER ANNUM,1820.00,251272.70,0.0,0.0,-4827.25,246445.45
3923539,2021,2.0,OFFICE OF THE MAYOR,WOLFE,EMILIA,M,01/01/2014,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.00,PER ANNUM,1820.00,251272.70,0.0,0.0,-4827.25,246445.45
3923536,2021,2.0,OFFICE OF THE MAYOR,ANGLIN,LAURA,L,01/03/2017,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.00,PER ANNUM,1820.00,251272.70,0.0,0.0,-4827.25,246445.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4369734,2021,2.0,OFFICE OF THE MAYOR,MULLINS-KING,TAURA,N,11/26/2018,MANHATTAN,MAYORAL OFFICE ASSISTANT,CEASED,51500.00,PER ANNUM,0.00,0.00,0.0,0.0,1294.54,1294.54
4382678,2021,2.0,OFFICE OF THE MAYOR,TALAMO,RACHEL,NaN,11/26/2018,MANHATTAN,STAFF ASSISTANT,CEASED,47380.00,PER ANNUM,0.00,0.00,0.0,0.0,813.40,813.40
4409782,2021,2.0,OFFICE OF THE MAYOR,ZANGRILLO,DENISE,NaN,12/13/2019,MANHATTAN,COLLEGE AIDE,CEASED,17.00,PER HOUR,22.25,378.25,0.0,0.0,0.00,378.25
4444237,2021,2.0,OFFICE OF THE MAYOR,KHATIBI,SEAN,P,12/07/2015,MANHATTAN,SPECIAL ASSISTANT,CEASED,54643.00,PER ANNUM,0.00,0.00,0.0,0.0,250.00,250.00
4454335,2021,2.0,OFFICE OF THE MAYOR,ROSADO,ANGELA,NaN,08/30/2018,MANHATTAN,MAYORAL OFFICE ASSISTANT,CEASED,32.64,PER HOUR,4.25,138.72,0.0,0.0,5.44,144.16

#### Calculate the Mayor's (Bill De Blasio) 2021 total gross pay

In [24]:
nyc_2021[
    (nyc_2021['First Name'] == 'BILL') 
    & (nyc_2021['Last Name'] == 'DE BLASIO')
    ]

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Total Gross Paid
3923481,2021,2.0,OFFICE OF THE MAYOR,DE BLASIO,BILL,NaN,01/01/2014,MANHATTAN,MAYOR,ACTIVE,258750.0,PER ANNUM,1820.0,258021.79,0.0,0.0,-4956.9,253064.89

#### Calculate average base salary per work location

In [25]:
# Create a SeriesGroupBy object for average base salary by work location

avg_base_sal = nyc_2021['Base Salary'].groupby(nyc_2021['Work Location Borough'])
avg_base_sal

In [26]:
# Calculate mean average base salary and sort lowest to highest

avg_base_sal.mean().sort_values(ascending = True)

Work Location Borough
NASSAU            29930.476500
MANHATTAN         43044.492124
BRONX             55290.460386
ORANGE            57403.000000
RICHMOND          58241.712893
QUEENS            58846.691720
BROOKLYN          59288.815687
DUTCHESS          60963.991379
PUTNAM            63959.932895
DELAWARE          65365.190366
WESTCHESTER       68429.795154
SCHOHARIE         70127.428571
SULLIVAN          72212.089297
GREENE            72366.213333
ULSTER            79805.588939
ALBANY            91296.344000
OTHER            120124.578298
WASHINGTON DC    133559.666667
Name: Base Salary, dtype: float64

#### Identify the highest base salary at the Washington, DC work location (the location with the highest mean base salary)

In [27]:
# Filter employees at Washington, DC location

washdc = nyc_2021[nyc_2021["Work Location Borough"].isin(['WASHINGTON DC'])]


# Sort by base salary, highest to lowest

washdc.sort_values(by='Base Salary', ascending=False)

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Total Gross Paid
3932324,2021,2.0,OFFICE OF THE MAYOR,KAGAN STERNHELL,REBECCA,K,10/01/2019,WASHINGTON DC,EXECUTIVE AGENCY COUNSEL,ACTIVE,178190.0,PER ANNUM,1820.0,177688.35,0.0,0.0,-3258.90,174429.45
4315554,2021,858.0,DEPT OF INFO TECH & TELECOMM,SEVILLIA,MAX,NaN,03/12/2018,WASHINGTON DC,ADMINISTRATIVE PUBLIC INFORMATION SPECIALIST,CEASED,177904.0,PER ANNUM,0.0,0.00,0.0,0.0,5833.55,5833.55
4110351,2021,2.0,OFFICE OF THE MAYOR,BISHOP,WALTER,J,11/19/2018,WASHINGTON DC,SPECIAL ASSISTANT,CEASED,154500.0,PER ANNUM,840.0,71100.79,0.0,0.0,3024.86,74125.65
3953011,2021,25.0,LAW DEPARTMENT,CONWAY,KIMBERLY,D,04/17/2017,WASHINGTON DC,ASSISTANT CORPORATION COUNSEL,ACTIVE,142057.0,PER ANNUM,1820.0,141657.13,0.0,0.0,-2177.12,139480.01
4070360,2021,2.0,OFFICE OF THE MAYOR,LOPEZ,ALFONSO,NaN,01/11/2016,WASHINGTON DC,ASSISTANT LEGISLATIVE REPRESENTATIVE,ACTIVE,89624.0,PER ANNUM,1820.0,89371.67,0.0,0.0,110.33,89482.00
4156446,2021,2.0,OFFICE OF THE MAYOR,HUNT,JAMES,A,02/22/2016,WASHINGTON DC,SPECIAL ASSISTANT,ACTIVE,59083.0,PER ANNUM,1820.0,58916.77,0.0,0.0,695.43,59612.20